# Actual location where these hyperparams shall be stored: .py310_tf_env\lib\site-packages\rl_zoo3\hyperparams\dqn.yml

TrafficEnv-DQN-0-v0:
  n_timesteps: 100000
  learning_rate: 1e-4
  buffer_size: 100000
  learning_starts: 1000
  batch_size: 32
  tau: 1.0
  gamma: 0.99
  train_freq: 4
  target_update_interval: 500
  exploration_fraction: 0.1
  exploration_final_eps: 0.05