FROM nvidia/cuda:11.8.0-base-ubuntu22.04

# Set BASH as the default shell for all RUN commands in this Dockerfile
# SHELL ["/bin/bash", "-c"]

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

LABEL maintainer="Catalin NICULESCU (catalin-niculescu@ensity.eu)"
LABEL Description="Dockerised Simulation of Urban MObility(SUMO)"

RUN apt-get update && apt-get install -y software-properties-common python3-software-properties

RUN add-apt-repository ppa:sumo/stable
RUN apt-get update && apt-get install -y sumo sumo-tools sumo-doc
ENV SUMO_HOME=/usr/share/sumo
ENV PATH=$PATH:$SUMO_HOME/bin

RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y \
    python3.7 \
    python3-distutils \
    python3-pip \
    python3-dev \
    python3-apt \
    libopenmpi-dev \
    zlib1g-dev \
    cmake \
    curl \
    unzip \
    git

RUN ln -s /usr/lib/python3/dist-packages/apt_pkg.cpython-310-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/apt_pkg.so

RUN apt-get install -y python3.7 python3.7-dev
RUN apt-get install -y python3.7 python3.7-distutils
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
RUN pip3 install --upgrade pip \
    tensorflow-gpu==1.15.0 \
    stable-baselines[mpi]==2.10.0 \
    numpy \
    scipy \
    matplotlib \ 
    pandas \
    traci \
    psutil \
    protobuf==3.20.* \
    gym==0.21.0 \
    setuptools==65.5.0 \
    importlib-metadata==4.13.0

WORKDIR /app
COPY . /app

# Install VS Code
RUN apt-get update && apt-get install -y wget gpg
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
RUN install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
RUN sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
RUN apt-get update && apt-get install -y code

RUN curl -fsSL https://code-server.dev/install.sh | sh

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Clone the Speed Harmonization project repository
RUN git clone https://github.com/nyculescu/phd_speed_harmo_v3.git /app/phd_speed_harmo_v3

# Set the working directory
WORKDIR /app/phd_speed_harmo_v3

RUN chown -R vscode:vscode /app/phd_speed_harmo_v3

# set up SSH keys for GitHub authentication
RUN mkdir -p ~/.ssh
RUN ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
RUN git config --global url."git@github.com:".insteadOf "https://github.com/"
RUN cat /root/.ssh/id_rsa.pub
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts
RUN git config --global user.email "cn.cata@gmail.com"
RUN git config --global user.name "Catalin Niculescu"
# add the generated ssh to https://github.com/settings/keys

# Install Python extension for VS Code
# RUN mkdir -p ~/.vscode/extensions \
#     && curl -JL https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/latest/vspackage -o /tmp/python.vsix \
#     && unzip /tmp/python.vsix -d ~/.vscode/extensions/ms-python.python \
#     && rm /tmp/python.vsix

# ENTRYPOINT ["python3"]

### Build the Docker image with the following command from the folder containing the docker file:
# With cache, custom /> docker build -f Dockerfile_py37_tf1 -t phd-speed-harmo:py37-tf1 .
# Without cache /> docker builder prune --all --force && docker build --no-cache -t phd-speed-harmo .
# Without cache, custom /> docker build --no-cache -f Dockerfile_py37_tf1 -t phd-speed-harmo:py37-tf1 .

### After building the image, you can run the container with the following command:
# download and install VcXsrv, then configure it like this:
    # 1. Choose "Multiple windows" in the first screen.
    # 2. Select "Start no client" in the second screen.
    # 3. In the "Extra settings" screen:
        # 3.1. Check "Disable access control"
        # 3.2. Optionally, check "Native opengl" (this can help with some applications)
    # 4. Click "Finish" to start the X server.
# Get the IP address of the host machine with /> ipconfig
# Start Docker container/> docker run --gpus all -it --rm -e DISPLAY=192.168.0.37:0.0 phd-speed-harmo:py37-tf1 bash
# Start Docker container V2/> docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -it --rm -e DISPLAY=192.168.0.37:0.0 phd-speed-harmo:py37-tf1 bash
# /> docker run -it --rm -e DISPLAY=host.docker.internal:0.0 -v /tmp/.X11-unix:/tmp/.X11-unix phd-speed-harmo:py37-tf1 code

# Inside the Docker container, to open SUMO GUI run:
    # /> export LIBGL_ALWAYS_INDIRECT=1
    # /> /usr/bin/sumo-gui

# To open VS Code GUI run:
    # /> docker run --gpus all -it --rm -e DISPLAY=host.docker.internal:0.0 -v /tmp/.X11-unix:/tmp/.X11-unix -e DONT_PROMPT_WSL_INSTALL=1 --user=vscode phd-speed-harmo:py37-tf1 /bin/bash
    # Inside the Docker /> code --no-sandbox